### ISSUE TITLE
Amazing but...

### ISSUE THREAD

**Issue by jackttcoms** [Anduin2017/jquery-disable-with#1]
This is amazing! Just what I was looking for but could you add a minor update to prevent the button from changing when a field if required! Thanks

https://gyazo.com/da91914aebeb4aaca4531c69f61e07bf

```
<form action="index.php" method="post">
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" required="" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" required="" id="exampleInputPassword1" placeholder="Password">
  </div>
    <input type="submit" value="Signing in..." data-disable-with="Signing in..." class="btn btn-primary">
</form>
```

**Comment by Anduin2017** [comment]
OK. Leave this to me.

But before my fix, it seems that this plugin already supoorts jquery validation. Try it here: 

https://www.aiursoft.com/auto/goauth

The form won't submit if you didn't not input your email. For more document about how to use this with jquery validation, please wait for me. I will finish it in two or three days.

Thanks again for your contribution!

**Comment by Anduin2017** [comment]
Nope. That server was located in the U.S. Could you please tell me your error info? That really helps.

**Comment by jackttcoms** [comment]
Of course. Here is a screenshot: 
![image](https://user-images.githubusercontent.com/26184209/50044153-3b72d380-0077-11e9-9eea-7da33a3bb755.png)
![image](https://user-images.githubusercontent.com/26184209/50044162-69581800-0077-11e9-88a5-d636f9318c17.png)


I am from UK as well if that helps! I have tried Firefox & Chrome

**Comment by jackttcoms** [comment]
Ok ye, very odd! Went on VPN, now works fine but when disable vpn issue comes back! Thanks

**Comment by Anduin2017** [comment]
Please try to upgrade your `jquery-disable-with` to `1.2.0`. I guess I have successfully solved your issue.

**Comment by jackttcoms** [comment]
ALL FIXED 💯 You are the best thanks so much and again great site! Love your auth system. 👍
